### ISSUE TITLE
The `done` parameter for the `.paginate()` callback should not be optional

### ISSUE THREAD

**Issue by ptomulik** [octokit/plugin-paginate-rest.js#259]
In almost all overloads of ``PaginateInterface`` the user-defined ``mapFn`` is guaranted to be provided with ``done`` argument, except in one case below:

https://github.com/octokit/plugin-paginate-rest.js/blob/1c0e4f23cae04035a3db31894c8728084e1874fe/src/types.ts#L182

Is this intentional? If so, then what is the reason?

**Comment by gr2m** [comment]
I'm pretty sure that's an oversight. Would you like to send a pull request to fix the typing?
