### ISSUE TITLE
Writing tests for a custom function using octokit.paginate

### ISSUE THREAD

**Issue by Belco90** [octokit/plugin-paginate-rest.js#373]
Hi there! This is not to report an issue with the plugin itself, but to get some guidance about how to write some tests for a function using `octokit.paginate`.

I basically have a React hook based on React Query which is wrapping a call to `octokit.paginate`. The idea is to fetch the first 1k releases to allow the user to filter them in [Octoclairvoyant](octoclairvoyant.vercel.app/).

The functionality is working fine in the actual app, but I'm trying to write some tests with Jest + React Hooks Testing Library and I can't figure out how to keep paginating the hook.

This is the PR where you can see a test failing, expecting 1k releases fetched but got just 100 (first page of releases): https://github.com/octoclairvoyant/octoclairvoyant-webapp/pull/767

It seems I need to trigger the next tick for `octokit.paginate` iterator, but I don't know how. I've used both `octokit.paginate` and `octokit.paginate.iterator` but both fail in the same way. I've tried to use Jest's fake timers but I can't run it to the next tick. I've tried to wait for different booleans from React Query, but after fetching the first page it's always finished.

Any clue where the problem could be located? Thanks in advance!

**Comment by timrogers** [comment]
@Belco90 Sorry to come to this issue so late, but did you ever have any luck with this?

**Comment by Belco90** [comment]
Hey @timrogers! No worries. I didn't find a way to test the React hook using `octokit.paginate` with Testing Library. I'm only able to test this with Cypress, but it generates a really slow test.

**Comment by Belco90** [comment]
Closing since it's not relevant anymore.
