### ISSUE TITLE
[MAINT]: "Add to Octokit Project" action fails due to missing token

### ISSUE THREAD

**Issue by oscard0m** [octokit/plugin-paginate-rest.js#489]
### What happened?

PR Check fails because of a missing GitHub Token:

> Error: Input required and not supplied: github-token

### Versions

5.0.1

### Relevant log output

https://github.com/octokit/plugin-paginate-rest.js/actions/runs/3863366872/jobs/6585514731

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This workflow is standard across all Octokit repos.

Why would this issue only happen here?

**Comment by oscard0m** [comment]
> This workflow is standard across all Octokit repos.
> 
> Why would this issue only happen here?

My guess is the secret of GITHUB_TOKEN is missing. Could be that?

**Comment by wolfy1339** [comment]
@kfcampbell @nickfloyd Can you take a look at this?

**Comment by gr2m** [comment]
The fix is to remove these two lines

```yml
  pull_request:
    types: [reopened, opened]
```

Pull requests from forks or dependabot don't have access to repository secrets when triggered by `pull_request`, only when triggered by `pull_request_target`

**Comment by nickfloyd** [comment]
I added a continue-on-error to all of them, assuming it would make the workflow optional - it sounds like that was not the case.

Yeah, I ran into the other scenario and was trying to reproduce it.  Where the following does not work for all repos:

```
  pull_request_target:
    types: [reopened, opened]
```

I'll remove the other for now, given that way is being deprecated.

**Comment by nickfloyd** [comment]
This should fix it: https://github.com/octokit/.github/pull/34
