### ISSUE TITLE
[BUG]: @octokit/types@8.2.0 incompatible with @octokit/plugin-paginate-rest@5.0.1

### ISSUE THREAD

**Issue by bcoe** [octokit/plugin-paginate-rest.js#498]
### What happened?

When upgrading to the latest version of @octokit/types, typescript throws compilation errors.

### Versions

@octokit/types@8.2.0 incompatible with @octokit/plugin-paginate-rest@5.0.1

### Relevant log output

```shell
node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:848:33 - error TS2339: Property 'PUT /organizations/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}' does not exist on type 'Endpoints'.

848             response: Endpoints["PUT /organizations/{org}/codespaces/secrets/{secret_name}/repositories/{repository_id}"]["response"];
                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/@octokit/plugin-rest-endpoint-methods/dist-types/generated/parameters-and-response-types.d.ts:859:60 - error TS2339: Property 'PUT /organizations/{org}/codespaces/secrets/{secret_name}' does not exist on type 'Endpoints'.

859             parameters: RequestParameters & Omit<Endpoints["PUT /organizations/{org}/codespaces/secrets/{secret_name}"]["parameters"], "baseUrl" | "headers" | "mediaType">;
                             
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
This is normal, as the packages all depend on each other and need to be kept in sync

A new release of this package needs to be released with the update to `@octokit/types`

**Comment by wolfy1339** [comment]
That can be arranged. A major version bump can be done. Sorry for the troubles!

However, even with a feature release, the different packages still need to be kept in sync, as they all cascade off one another

**Comment by wolfy1339** [comment]
That can be arranged. A major version bump can be done. Sorry for the troubles!

However, even with a feature release, the different packages still need to be kept in sync, as they all cascade off one another

**Comment by benjdlambert** [comment]
@wolfy1339 thanks for the reply! Yeah, I think in order to fix it that 8.2.0 release will either need to be unpublished, or 8.2.1 to be released with the previous generated stuff before the PR, and then a followup release of 9.0.0 with the contents of the PR.

> However, even with a feature release, the different packages still need to be kept in sync, as they all cascade off one another

Yep totally get that for new features etc!

**Comment by wolfy1339** [comment]
I've started submitting PRs to remedy the situation
Starting off with: https://github.com/octokit/types.ts/pull/501

**Comment by bcoe** [comment]
Thank you @wolfy1339
