### ISSUE TITLE
[BUG]: Published package still require @octokit/core@5, which breaks peer dependency

### ISSUE THREAD

**Issue by siketyan** [octokit/plugin-paginate-rest.js#622]
### What happened?

Though https://github.com/octokit/plugin-paginate-rest.js/blob/631e72609378562fd96c1ae2e8163db52174e497/package.json#L33 specifies `@octokit/core@>=6` as peer dependency, the published package still require `@octokit/core@5`. This breaks peer dependency on our environment.

```
 ERR_PNPM_PEER_DEP_ISSUES  Unmet peer dependencies

.
├ @octokit/rest 21.0.0
├─┬ @octokit/plugin-paginate-rest 11.3.1
│ └── ✕ unmet peer @octokit/core@5: found 6.1.2 in @octokit/rest
└─┬ @octokit/plugin-rest-endpoint-methods 13.2.2
  └── ✕ unmet peer @octokit/core@^5: found 6.1.2 in @octokit/rest
```

```
❯ pnpm show @octokit/plugin-paginate-rest@11.3.1

@octokit/plugin-paginate-rest@11.3.1 | MIT | deps: 1 | versions: 109
Octokit plugin to paginate REST API endpoint responses
https://github.com/octokit/plugin-paginate-rest.js#readme

keywords: github, api, sdk, toolkit

dist
.tarball: https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-11.3.1.tgz
.shasum: fe92d04b49f134165d6fbb716e765c2f313ad364
.integrity: sha512-ryqobs26cLtM1kQxqeZui4v8FeznirUsksiA+RYemMPJ7Micju0WSkv50dBksTuZks9O5cg4wp+t8fZ/cLY56g==
.unpackedSize: 203.5 kB

(omit)
```

```
❯ curl -sL https://registry.npmjs.org/@octokit/plugin-paginate-rest/-/plugin-paginate-rest-11.3.1.tgz | tar -xf -
❯ cat package/package.json | jq '.peerDependencies'
{
  "@octokit/core": "5"
}
```

### Versions

Node.js v20.15.0
pnpm v9.4.0

@octokit/core 6.1.2
@octokit/rest 21.0.0
@octokit/plugin-paginate-rest 11.3.1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by wolfy1339** [comment]
Please don't use 11.3.1

It's a special back port release for CJS users, which is not published to the main npm tag

The proper release to use is 11.3.0

**Comment by viceice** [comment]
@wolfy1339 that didn't solve anything. the package managers will resolve it to version v11.3.1 (at least pnpm)

**Comment by wolfy1339** [comment]
You can force your package manager to use whichever version you want. In the end you can manually edit your lockfile and `package.json` to suit your needs.

I triggered a new release that should fix the issue

**Comment by siketyan** [comment]
Thank you for quick response and the new release!

Writing overrides in package.json resolved the problem for now:

```json
{
  "pnpm": {
    "overrides": {
      "@octokit/plugin-paginate-rest": "11.3.0",
      "@octokit/plugin-rest-endpoint-methods": "13.2.1"
    }
  }
}
```

The new release also works.
A new release for plugin-rest-endpoint-methods would also be helpful.

**Comment by wolfy1339** [comment]
fyi, @viceice it's probable best not to have `semantic-release` in your dependencies, but rather use a tool like `npx`

It avoids all issues like this and any compability issues that arise when you use different Octokit versions that what `semantic-release` usees

**Comment by viceice** [comment]
> fyi, @viceice it's probable best not to have `semantic-release` in your dependencies, but rather use a tool like `npx`
> 
> It avoids all issues like this and any compability issues that arise when you use different Octokit versions that what `semantic-release` usees

That would make things more complicated, because we need a lot plugins, which are not installed by default.

**Comment by wolfy1339** [comment]
We install plugins as `devDependencies` but not the core `semantic-release` packages here in Octokit

**Comment by gr2m** [comment]
> That would make things more complicated, because we need a lot plugins, which are not installed by default.

I install plugins as needed as part of the release workflow. I wish there was something like `releaseDependencies`
